### ISSUE TITLE
Add two-mode to MELPA

### ISSUE THREAD

**Issue by mcandre** [klacke/yaws#144]
It would be highly convenient to add two-mode to [MELPA](http://melpa.milkbox.net/).

* yaws wouldn't be required to edit `.yaws` files.
* two-mode could be setup by Emacs users by typing `M-x package-install RET two-mode RET`.

**Comment by luisgerhorst** [comment]
:+1:

**Comment by vinoski** [comment]
There are already a number of emacs packages that support multiple mode editing; [here's a good list](http://emacswiki.org/emacs/MultipleModes). Some of these are in MELPA. Note also that `two-mode-mode` is on the list, and its home and author are mentioned there too.

**Comment by capflam** [comment]
I guess that issue can be closed :)
