### ISSUE TITLE
enable travis

### ISSUE THREAD

**Issue by andreineculau** [klacke/yaws#190]
You have a travis configuration file in the repo,
but you don't seem to have an active github service configuration for travis (Settings -> Webhooks & Services). On purpose?

https://travis-ci.org/klacke/yaws

**Comment by capflam** [comment]
@klacke, Sorry to bother you about that, but it would be nice to enable travis on Yaws. This is a good way to test it on all supported Erlang releases. I use my Yaws clone for now, but this is not really handy :)

**Comment by klacke** [comment]
Ok - done - I hope. First build running now ...

**Comment by capflam** [comment]
Thanks @klacke, it works ! I've also enabled build of pull requests.
