### ISSUE TITLE
hyperlinks in HTML 5

### ISSUE THREAD

**Issue by dino-r** [klacke/yaws#196]
I was just fiddling around with EHTML and noticed that yaws refuses put the HTML element 'a' around a block, say a 'div'. As of HTML 5, making a block a hyperlink is perfectly valid. Could you add the 'a' tag to the block level elements?

**Comment by vinoski** [comment]
Can you provide an example of what you're asking for?

**Comment by dino-r** [comment]
Oh boy. I've found the reason for my issue, but it's not related to yaws. Sorry, for the inconvenience. Anyway, thanks for the quick reply!

**Comment by vinoski** [comment]
OK, thanks for following up. Closing this issue.
