### ISSUE TITLE
Does Yaws server support ruby on rails and php websites?

### ISSUE THREAD

**Issue by topstarnetwork** [klacke/yaws#198]
Does Yaws server support ruby on rails and php websites?
Regards, Heather

**Comment by capflam** [comment]
Yaws can be plugged on a FastCGI server. I have not enough knowledge on Ruby-on-Rails to answer, but for PHP, you can use [HHVM](http://hhvm.com) or [PHP-FPM](http://php-fpm.org).

**Comment by topstarnetwork** [comment]
What about asp.net aspx, does Yaws support it?

**Comment by capflam** [comment]
As for Ruby-on-Rails, I'm not an ASP.NET expert. But I can make a generic answer. 	From the moment a language supports FastCGI, Yaws can be used.

**Comment by topstarnetwork** [comment]
Just back for a littel question, what do you mean with "Yaws can be plugged on a FastCGI server"?
Do you mean I can plug it to apache server?
Could you please explain me,
regards, Heather

**Comment by capflam** [comment]
Apache is not a FastCGI server. It is a HTTP server, like Yaws. A FastCGI server is a server that talks with clients using the FastCGI protocol. This seems to be hazy for you. I suggest you to read documentation about FastCGI and web server architectures in general to get some understanding on how things work. Of course, you can read [Yaws documentation](http://yaws.hyber.org/yaws.pdf). The chapter 10 talks about FastCGI :)
