### ISSUE TITLE
Yaws server webmin/virtualmin plugin

### ISSUE THREAD

**Issue by topstarnetwork** [klacke/yaws#203]
Hello,
I need a  yaws server webmin/virtualmin plugin to manage yaws server withing my webmin/virtualmin directly,
could you please tell me if such a plugin exist and if not howmuch would it cost to cevelop it,
regards, Miss Riverso

**Comment by capflam** [comment]
Hi,

AFAIK, no such plugin exists for Yaws. I don't see any problem to generate Yaws configuration from a web interface. So I guess it could be done. But I never develop virtualmin plugins, so I cannot tell you how long it would take.

**Comment by topstarnetwork** [comment]
Would you know any freelancer who would be intrested to develop this webmin/virtualmin yaws plugin for me?
Regards, Heather

**Comment by klacke** [comment]
I don't know. Maybe reach out on the regular erlang list, I'm not sure how fond they are on that type of posts though. There's a yaws mailing list too which at least reaches more people than a post on github like this.

**Comment by vinoski** [comment]
Find details of the Yaws mailing list here: https://lists.sourceforge.net/lists/listinfo/erlyaws-list . As @klacke suggested, I recommend sending a message there to see if anyone is available to do this work.

**Comment by topstarnetwork** [comment]
Thanks, I will check it out.
