### ISSUE TITLE
Embedded: Cannot disable memory caching

### ISSUE THREAD

**Issue by luisgerhorst** [klacke/yaws#221]
I'm starting Yaws like this in my app: 
```erlang
yaws:start_embedded(
  priv_dir(["www"]),
  [{port, env(port)},
   {listen, env(listen)},
   {appmods, [{"/api/", rpmhttp_api}]}],
  [{logdir, priv_dir(["yaws", "logs"])},
   {mnesia_dir, priv_dir(["yaws", "mnesia"])}]),
```
and I have this in my `myapps.config` that I supply to the VM using `erl`'s `-config` flag:
```erlang
[{yaws, [{debug, true},
         {embedded, true}]}]
```
Anyway, when I change a `.yaws` file in the document root, the changes only appear on the site after about 30 seconds.

I've tried multiple browsers with caching disabled. ~~I also tried directly passing `{cache_refresh_secs, 0}` in the global config.~~ When I enter `application:get_env(yaws, debug)` I get `{ok, true}`.

**Comment by luisgerhorst** [comment]
__Update:__ Please excuse me, `{cache_refresh_secs, 0}` works. I anyway wonder why the environment variable `debug` has no effect. I could not find any documents on it, how can I easily run Yaws in development mode (→ I want changes in my `.yaws` files to take effect immediately) when running it embedded? [`yaws.hrl:95`](https://github.com/klacke/yaws/blob/master/include/yaws.hrl#L95) says `cache_refresh_secs` is automatically set to 0 when in debug mode (what I would guess means that the environment variable `debug` is set to `true`).

**Comment by capflam** [comment]
Hi,

You're right. There is a bug here. When the environment variable `debug` is set to `true`, `cache_refresh_secs` is set to `0` when Yaws is started with a configuration file but not in embedded mode.
I'll fix that very soon.
