### ISSUE TITLE
Escape EHTML attribute values

### ISSUE THREAD

**Issue by luisgerhorst** [klacke/yaws#222]
Suppose I have something like this:
```erl
{p, {'data-something', String}, "Hello"}
```
Because `String` could contain a `"` the whole site can end up completely broken. I know that this may not be trivial but I think it's what you would expect, otherwise EHTML is not really useful (expect better indenting) because you are facing the same problems you would also have if you were using `{html, ...}`.

**Comment by vinoski** [comment]
There are a variety of tests [here](https://github.com/klacke/yaws/blob/master/test/eunit/ehtml_test.erl#L24-L33) that have quotes embedded inside quoted data in ehtml. How does your test case differ from those test cases? Can you submit a test case here that reproduces the problem you're seeing?

**Comment by luisgerhorst** [comment]
Sorry. I see that I have to use `{check, Key, Value}` not simply `{Key, Value}`. Is this documented somewhere? Also, I would suggest making it the default.
