### ISSUE TITLE
Update to OTP 18.0

### ISSUE THREAD

**Issue by tyre** [klacke/yaws#226]
As part of https://github.com/Homebrew/homebrew/pull/41035 we need to update yaws to OTP 18.0.

@klacke Do you have time to take this on?

Thanks!

**Comment by vinoski** [comment]
@tyre I'm working on it, hope to complete the work soon.

**Comment by tyre** [comment]
Awesome, thanks @vinoski!

**Comment by vinoski** [comment]
Fixed in commit 316b4c60.

**Comment by tyre** [comment]
This is amazing, thanks @vinoski!

**Comment by tyre** [comment]
@vinoski Could we issue a new version that includes the latest commit? Homebrew goes off of archives which works best with git tags: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/yaws.rb#L4

**Comment by vinoski** [comment]
@tyre To the best of my knowledge only @klacke can create a full release. Can you get by with just a git tag?

**Comment by optikfluffel** [comment]
@vinoski I think a git tag should do because then we'd have a new archive to download and could update the homebrew formula accordingly

**Comment by vinoski** [comment]
@optikfluffel and @tyre: I created the tag `yaws-erlang-18` which isn't an official regular Yaws release but instead is essentially just yaws 1.99 with modifications to run on Erlang 18.0. Hopefully [the tarball for this tag](https://github.com/klacke/yaws/archive/yaws-erlang-18.tar.gz) will work for your purposes.

**Comment by klacke** [comment]
Ok, all good. Let me try to build a new release ASAP

**Comment by optikfluffel** [comment]
@klacke should I cancel my homebrew PR and wait for you?

**Comment by klacke** [comment]
Ok - we're good . New rel tested and built. Looks good, and it gets the impressive relno 2.0
http://yaws.hyber.org/download/yaws-2.0.tar.gz

**Comment by klacke** [comment]
Or I guess you pull from github, that's fine the tag is yaws-2.0

**Comment by vinoski** [comment]
@klacke I assume you'll be creating a tag `yaws-2.0`? If so I think I'll delete the `yaws-erlang-18` tag since it serves no purpose anymore.

**Comment by optikfluffel** [comment]
@klacke I could use the yaws-2.0 tag here at Github too, since yaws.hyber.org doesn't like https :tongue:

**Comment by vinoski** [comment]
The `yaws-2.0` tag was added 2015-Jul-13, so closing this issue.
