### ISSUE TITLE
how to reload the subconfig for vhosts

### ISSUE THREAD

**Issue by leeyisoft** [klacke/yaws#229]
I have modified the configuration of the virtual site, how to reload the configuration file；
Also, how to use regular expressions like nginx url rewrite function；
For example, in the browser to input 
http://domain/new/1.html  or http://domain/news/1.html 
and yaws Redirected it to 
/news/detail.yaws file

**Comment by capflam** [comment]
To reload Yaws configuration, you can use '--hup' option of the yaws script. You can also call yaws:hup/0.
About redirect rules, unfortunately, regex are no supported. But you could write a arg_rewrite module or an appmod to do what you want.
