### ISSUE TITLE
User-defined authmod stopped working since Yaws 2.0

### ISSUE THREAD

**Issue by phonohawk** [klacke/yaws#232]
After the commit 6cfcabd46a1db887e442130ba271d9831e4a5cd2 being introduced, user-defined authmod modules stopped working due to record type mismatch `{badrecord,auth}`. I wonder what was the intention of the commit in the first place. `Auth_H` isn't a `#auth{}`, is it?

**Comment by phonohawk** [comment]
I confirmed that reverting the commit fixes the problem.

**Comment by vinoski** [comment]
Not sure of the intent of the change, but the fact that it failed means there should be a regression test in place for this to prevent this sort of error.

**Comment by capflam** [comment]
Hi,
To be honest, I cannot remember why I've pushed this change. It seems silly. I think it should be reverted as @phonohawk  suggested.

**Comment by capflam** [comment]
Thanks !
