### ISSUE TITLE
missing Host header should automatically trigger 400 Bad Request

### ISSUE THREAD

**Issue by andreineculau** [klacke/yaws#239]
from http://tools.ietf.org/html/rfc2616#section-14.23

```
   ... All
   Internet-based HTTP/1.1 servers MUST respond with a 400 (Bad Request)
   status code to any HTTP/1.1 request message which lacks a Host header
   field.
```

**Comment by vinoski** [comment]
There's definitely a bug here, but note that even with it fixed, you'll need to set the `pick_first_virthost_on_nomatch` config variable to `false` if you want a missing `Host` header to result in a 400 status.

**Comment by andreineculau** [comment]
I don't see the reason for that for HTTP/1.1 requests (though I understand
why that's the flow for HTTP/1.0 requests). That would be in clear
violation of the HTTP/1.1 RFC (sent a slightly outdated link before to the
infamous RFC2616)

http://tools.ietf.org/html/rfc7230#section-5.4

```

   A server MUST respond with a 400 (Bad Request) status code to any
   HTTP/1.1 request message that lacks a Host header field and to any
   request message that contains more than one Host header field or a
   Host header field with an invalid field-value.

```

On Fri, Sep 25, 2015 at 3:48 AM, Steve Vinoski <notifications@github.com>
wrote:

> There's definitely a bug here, but note that even with it fixed, you'll
> need to set the pick_first_virthost_on_nomatch config variable to false
> if you want a missing Host header to result in a 400 status.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/klacke/yaws/issues/239#issuecomment-143099845>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by vinoski** [comment]
Backward compatibility. The `pick_first_virthost_on_nomatch` variable is for specifically checking for a `Host` header and choosing a virtual server if none is present. If we just flip the default setting of that variable, it will break some systems. Waiting for a substantial Yaws release to make that change so it can be better documented and advertised is a better move.

If every web application followed the RFCs perfectly, lots of things would be easier, but they don't, and servers often have to compensate.

**Comment by klacke** [comment]
So, yes the RFC says MUST, but I cannot see that we break anything by not following that. AFAICT the only thing we would accomplish by adhering wouldbe to make netcat,telnet based debugging a bit more cumbersome.

**Comment by andreineculau** [comment]
It broke my code, Klacke :) `#headers.host` should never be null if the
standard is followed.

On Sat, Sep 26, 2015 at 2:10 PM, Claes Wikstrom <notifications@github.com>
wrote:

> So, yes the RFC says MUST, but I cannot see that we break anything by not
> following that. AFAICT the only thing we would accomplish by adhering
> wouldbe to make netcat,telnet based debugging a bit more cumbersome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/klacke/yaws/issues/239#issuecomment-143427493>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by vinoski** [comment]
+1 to what @klacke says about tools like curl and netcat.

My plan for this issue is to fix it for the `pick_first_virthost_on_nomatch=false` case, but to leave the default `pick_first_virthost_on_nomatch=true` case working the same as it currently does.

**Comment by andreineculau** [comment]
FWIW `curl` is NOT a generic TCP tool like netcat and telnet. It actually
implements the HTTP protocol (and many more), thus you do not manually set
a `Host` header e.g.

```sh
$ curl -vsS http://example.com 2>&1 | grep Host
> Host: example.com
```

Flags are fine, no matter the reason (backwards compatibility, convenience,
etc).

On Sat, Sep 26, 2015 at 3:38 PM, Steve Vinoski <notifications@github.com>
wrote:

> +1 to what @klacke <https://github.com/klacke> says about tools like curl
> and netcat.
>
> My plan for this issue is to fix it for the
> pick_first_virthost_on_nomatch=false case, but to leave the default
> pick_first_virthost_on_nomatch=true case working the same as it currently
> does.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/klacke/yaws/issues/239#issuecomment-143436760>.
>



-- 
andreineculau.com <http://www.andreineculau.com>
