### ISSUE TITLE
yaws fails to start with Erlang 18.1

### ISSUE THREAD

**Issue by zuav** [klacke/yaws#240]
OS X 10.10.5, Erlang 18.1 (Homebrew)
Yaws's latest sources.
What I did:
make --prefix=/opt/yaws
make install
/opt/yaws/bin/yaws -i
Eshell V7.1  (abort with ^G)
1> 
=INFO REPORT==== 29-Sep-2015::21:27:59 ===
Yaws: Using config file /opt/yaws/etc/yaws/yaws.conf
1> 
=INFO REPORT==== 29-Sep-2015::21:27:59 ===
yaws debug:Add path "/opt/yaws/lib/yaws/examples/ebin"
1> 
=INFO REPORT==== 29-Sep-2015::21:27:59 ===
yaws debug:Add path "/opt/yaws/lib/yaws/examples/ebin"
1> 
=INFO REPORT==== 29-Sep-2015::21:27:59 ===
yaws debug:Running with id="default" 
Running with debug checks turned on (slower server) 
Logging to directory "/opt/yaws/var/log/yaws"
1> 
=INFO REPORT==== 29-Sep-2015::21:27:59 ===
Ctlfile : /Users/zuav/.yaws/yaws/default/CTL
1> 
=INFO REPORT==== 29-Sep-2015::21:27:59 ===
Yaws: Listening to 0.0.0.0:8000 for <2> virtual servers:
 - http://*:8000 under /opt/yaws/var/yaws/www
 - http://localhost:8000 under /var/folders/qf/_fj_8z_j0yxddzhh30nbxcj40000gn/T
1> 
=INFO REPORT==== 29-Sep-2015::21:27:59 ===
Yaws: Listening to 0.0.0.0:4443 for <1> virtual servers:
 - https://*:4443 under /var/folders/qf/_fj_8z_j0yxddzhh30nbxcj40000gn/T
1> 
=ERROR REPORT==== 29-Sep-2015::21:27:59 ===
** gen_event handler yaws_log_file_h crashed.
** Was installed in error_logger
** Last event was: {info_report,<0.33.0>,
                    {<0.35.0>,progress,
                     [{supervisor,{local,yaws_sup}},
                      {started,
                       [{pid,<0.38.0>},
                        {id,yaws_server},
                        {mfargs,
                         {yaws_server,start_link,
                          [{env,true,false,false,false,false,false,
                            "default"}]}},
                        {restart_type,permanent},
                        {shutdown,120000},
                        {child_type,worker}]}]}}
** When handler state == {<0.62.0>,"/opt/yaws/var/log/yaws/report.log",[]}
** Reason == {function_clause,
              [{error_logger_file_h,write_event,
                [{<0.62.0>,"/opt/yaws/var/log/yaws/report.log",[]},
                 {info_report,<0.33.0>,
                  {<0.35.0>,progress,
                   [{supervisor,{local,yaws_sup}},
                    {started,
                     [{pid,<0.38.0>},
                      {id,yaws_server},
                      {mfargs,
                       {yaws_server,start_link,
                        [{env,true,false,false,false,false,false,"default"}]}},
                      {restart_type,permanent},
                      {shutdown,120000},
                      {child_type,worker}]}]}}],
                [{file,"error_logger_file_h.erl"},{line,114}]},
               {error_logger_file_h,handle_event,2,
                [{file,"error_logger_file_h.erl"},{line,79}]},
               {gen_event,server_update,4,[{file,"gen_event.erl"},{line,538}]},
               {gen_event,server_notify,4,[{file,"gen_event.erl"},{line,520}]},
               {gen_event,handle_msg,5,[{file,"gen_event.erl"},{line,261}]},
               {proc_lib,init_p_do_apply,3,
                [{file,"proc_lib.erl"},{line,240}]}]}
1>

**Comment by vinoski** [comment]
Thanks, we already know about this and a fix is in progress.

**Comment by zuav** [comment]
Thanks for a quick fix.
It worked for me :)

**Comment by klacke** [comment]
Perfect fix, I'll build 2.0.1 with this as soon as I see the travis tests go through.
