### ISSUE TITLE
duplicated modules: json specified in json and yaws

### ISSUE THREAD

**Issue by joaohf** [klacke/yaws#244]
Hi, 

Could src/json.erl  be removed? I get the above when trying to generate a release.

Errors generating release 
          Duplicated modules: 
        json specified in json and yaws

I am using https://github.com/talentdeficit/json that has a json module.

How to deal with it?

**Comment by vinoski** [comment]
Can you exclude the yaws `json.erl` from your release?

**Comment by vinoski** [comment]
BTW I agree that it's likely time to remove `json.erl`. @klacke what do you think? It's been marked deprecated for quite awhile now.

**Comment by weisslj** [comment]
That would be great! We manually remove `json.erl` every time we upgrade yaws.

**Comment by klacke** [comment]
Fine by me, remove.
