### ISSUE TITLE
Insane Input...

### ISSUE THREAD

**Issue by Guido-Flawsec** [klacke/yaws#251]
On the page .................: http://yaws.hyber.org/query.yaws
The example [a]URL[/a] : http://yaws.hyber.org/man.yaws?page=cat

[#] Check this :

http://yaws.hyber.org/man.yaws?page=cat ............ = ###[OK]###

[#] Now note the "%" instead of "&" :::

http://yaws.hyber.org/man.yaws?page=cat%a .......... = "illegal character detected in query arg"
http://yaws.hyber.org/man.yaws?page=cat%aa ......... = "illegal character detected in query arg"
http://yaws.hyber.org/man.yaws?page=cat%ab ......... = "illegal character detected in query arg"
http://yaws.hyber.org/man.yaws?page=cat%ac ......... = "illegal character detected in query arg"
http://yaws.hyber.org/man.yaws?page=cat%ad ......... = "illegal character detected in query arg"
http://yaws.hyber.org/man.yaws?page=cat%ae ......... = "illegal character detected in query arg"
http://yaws.hyber.org/man.yaws?page=cat%ae ......... = "illegal character detected in query arg"
http://yaws.hyber.org/man.yaws?page=cat%ag ......... = ###[CRASH]###
http://yaws.hyber.org/man.yaws?page=cat%ah ......... = ###[CRASH]###
http://yaws.hyber.org/man.yaws?page=cat%ai ......... = ###[CRASH]###
........................................etc......... = ###[CRASH]###

**Comment by vinoski** [comment]
The `man.yaws` page is only meant to be a demo, not a production-quality system, but sure, I'll fix this.
