### ISSUE TITLE
parse_auth/1 in yaws.erl fails if password contains ':'

### ISSUE THREAD

**Issue by etnt** [klacke/yaws#267]
If the password contains ':', the call to string:tokens(Auth, ":") in parse_auth/1 will produce a list with length > 2 :
                                                                                                               
    ...            
    case string:tokens(Auth, ":") of                                                                                                                                                   
          [User, Pass] -> {User, Pass, Orig}; 
          _            -> {undefined, undefined, Orig}                                                                                                                                   
    end

**Comment by klacke** [comment]
Fixed in f9795f1317909d1716b37d140d491de10d7269b3
