### ISSUE TITLE
YAWS 2.0.2 (CPU usage)

### ISSUE THREAD

**Issue by stuart-thackray** [klacke/yaws#271]
Hi,

I am having a problem with yaws 2.0.2 where by it is using all the CPU & the processes never clears. This is a sporadically reoccurring issue.

The version installed is 2.0.2 downloaded from yaws webpage; and it is running standard config listen on one port (HTTP); with one appmod. Erlang Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:2:2] [async-threads:5] [hipe] [kernel-poll:true]

The below the reductions of the processes that seems to be looping. The below show the reductions visualised using https://github.com/zhongwencool/observer_cli. 

|o(OBSERVER)|e(ETS/SYSTEM)|a(ALLOCATOR)|db(MNESIA)|h(HELP)|recon:proc_count(reductions, 28, 0) Refresh:5000ms          4Days 21:34:6|
||01[||||||||||||||||||||||||||||||||||||||||||||||||||||||100.0%] |02[||||||||||||||||||||||||||||||||||||||||||||||||||||||100.0%]|
|Pos|Pid         | Reductions| Name or Initial Call          |    Memory|Msg Queue  |Current Function                               |
|1  |<0.13439.0> |58226097870| proc_lib:init_p/5             |     142824|0         |filename:dirname/4                             |
|2  |<0.13441.0> |57938397067| proc_lib:init_p/5             |      88640|0         |filename:dirname/4       

Linux shows the port(s) as only in closed wait state. 

 netstat -an | grep 8100
tcp        0      0 0.0.0.0:8100                0.0.0.0:*                   LISTEN      
tcp        1      0 10.27.103.111:8100          10.27.103.90:40292          CLOSE_WAIT  
tcp        1      0 10.27.103.111:8100          10.27.103.90:40282          CLOSE_WAIT 

Process info shows from a different node than the above shows. ( I have removed directories from the process info)

[{current_function,{filename,dirname,4}},
 {initial_call,{proc_lib,init_p,5}},
 {status,running},
 {message_queue_len,0},
 {messages,[]},
 {links,[<0.149.0>,#Port<0.3000135>]},
 {dictionary,[{sc,{sconf,10000,7,[],undefined,undefined,
                         "/home/......./site/static",[],
                         {0,0,0,0},
                         ".....:10000",[],undefined,49192,undefined,
                         [{"...../site/static",[]}],
                         nolimit,[],[],yaws_outmod,yaws_outmod,yaws_outmod,
                         yaws,yaws_log,[],undefined,
                         [yaws,php,cgi,fcgi],
                         [],
                         ["index.yaws","index.html","index.php"],
                         [],
                         [{listen_opts,[{backlog,1024}]}],
                         [],undefined,undefined,
                         {cgi,"/usr/bin/php-cgi"},
                         undefined,undefined,undefined,undefined}},
              {trace_filter,undefined},
              {outh,{outh,undefined,undefined,undefined,false,decide,
                          undefined,undefined,undefined,undefined,undefined,
                          undefined,undefined,undefined,undefined,undefined,
                          undefined,undefined,undefined,undefined,undefined,
                          undefined,undefined,undefined,undefined,undefined}},
              {gc,{gconf,"....../lib/yaws-2.0.2",false,1124,
                         "......./log",
                         ["......yaws-2.0.2/examples/ebin"],
                         [],[],infinity,nolimit,400,1000000,8000,nolimit,[],
                         10240,[],10000000,30,
                         ["...../examples/include"],
                         "/usr/bin/php-cgi","Yaws 2.0.2","10000",false,[],
                         yaws_session_server,8,undefined,
                         [inet]}},
              {gserv_pid,<0.149.0>},
              {'$ancestors',[<0.149.0>,yaws_server,yaws_sup,<0.140.0>]},
              {request_start_time,{1462,916444,962387}},
              {'$initial_call',{yaws_server,acceptor0,2}},
              {init_db,[{trace_filter,undefined},
                        {gc,{gconf,"....../lib/yaws-2.0.2",
                                   false,1124,"..../log",
                                   [".....yaws-2.0.2/examples/ebin"],
                                   [],[],infinity,nolimit,400,1000000,8000,
                                   nolimit,[],10240,[],10000000,30,
                                   ["....../yaws-2.0.2/examples/include"],
                                   "/usr/bin/php-cgi","Yaws 2.0.2","10000",
                                   false,[],yaws_session_server,8,undefined,
                                   [inet]}},
                        {gserv_pid,<0.149.0>},
                        {'$ancestors',[<0.149.0>,yaws_server,yaws_sup,
                                       <0.140.0>]},
                        {'$initial_call',{yaws_server,acceptor0,2}}]}]},
 {trap_exit,true},
 {error_handler,error_handler},
 {priority,normal},
 {group_leader,<0.139.0>},
 {total_heap_size,10957},
 {heap_size,4185},
 {stack_size,35},
 {reductions,1097669135866},
 {garbage_collection,[{min_bin_vheap_size,46422},
                      {min_heap_size,233},
                      {fullsweep_after,10},
                      {minor_gcs,10}]},
 {suspending,[]}]

I am not sure what else I could trace; obviously the loop is started in acceptor0/2 and the function is filename:dirname and I believe the function is filter_auths

Where this is happening the config can be a simple as below. 

logdir = ./log
id = 8100
<server localhost>
        port = 8100
        listen = 0.0.0.0
        docroot = ./site/static
        appmods = </, nitrogen_yaws exclude_paths Grid icons videos scripts images css nitrogen>
</server>

Is there any additional information I can provide? (I have looked at the code and haven't found any issue or solution)

**Comment by vinoski** [comment]
@stuart-thackray is this occurring during startup? Is the docroot directory particularly large or deep? Try setting `auth_skip_docroot = true` in your `<server>` config.

**Comment by stuart-thackray** [comment]
Will try that and see if reoccurs.

No it is not happening on startup; it is sporadically occurring and is only noticed due to the high CPU usage of the node/machine.

There always seems to be a connection visible in netstat; and as far as I remeber the connection state is always CLOSED_WAIT.

**Comment by klacke** [comment]
There is a function

$ yaws --debug-dump <file>

Which dumps state of the daemon - try that when the CPU peaks
and either have a look at the file or post it somewhere ...

You could also try some of the 'top' modules that float around
on the net and try to run that while CPU peaks.


/klacke

**Comment by stuart-thackray** [comment]
Thanks I will try both of these things and reopen the issue if when I can get more information.

**Comment by capflam** [comment]
I checked a little and I think I found the bug.

With a catchall appmod (on '/'), if a client sends a request on ```.``` or ```./path```, Yaws will loop infinitely on ```yaws_server:is_revproxy/3```. For all methods other than ```CONNECT```, this kind of requests is invalid. But, never mind, this is truly easy to fix. So I will push a fix very quickly.

Thanks

**Comment by stuart-thackray** [comment]
Thank you very much; Additional information I have found is that it was a vunaribility scanner i.e. https://www.alienvault.com/solutions/network-vulnerability-scanning

I can provide the yaws --debug-dump later if you need this information.

**Comment by capflam** [comment]
Thanks @stuart-thackray. But its ok, the bug is easy to reproduce and to fix.

And I made a mistake. In you case, the loop occurs in ```yaws_server:filter_auths/3```. But depending on the configuraiton, it can occur in ```yaws_server:is_revproxy/3``` or ```yaws_server:is_redirect_map/2```.

**Comment by capflam** [comment]
@stuart-thackray, I pushed a fix. Let me know if you still have any problem. Thanks !

**Comment by klacke** [comment]
I also just recently pushed, triggering a Travis build - that failed.
I reran once, and now your push triggered yet another run - that
also failed. All 3 failed differently - timeouts.

Maybe the travis servers are overloaded ...

/klacke

**Comment by stuart-thackray** [comment]
Thanks @capflam all good :+1: 

I manually made the same changes to the downloadable version of 2.0.2 and have reran the scanner; and there was no looping/CPU usage.

**Comment by capflam** [comment]
@klacke, You're right. There are recurrent problems with Travis. I'll plan to work on this issue. But I'm too busy for now.

**Comment by xlj** [comment]
@capflam we have use a low yaws version,i think i have the problem, i think about to upgrade my yaws version, before that ,i want to evaluation the influence，i believe it can not be trigger，. or ./path is not a correct request, http client can't sent it to yaws. can you tell me how can i recurrent this bug.

**Comment by xlj** [comment]
> Thank you very much; Additional information I have found is that it was a vunaribility scanner i.e. https://www.alienvault.com/solutions/network-vulnerability-scanning
> 
> I can provide the yaws --debug-dump later if you need this information.

you use "https://www.alienvault.com/solutions/network-vulnerability-scanning" trigger this bug?
