### ISSUE TITLE
Can we put websocket's callback beam file in a virtual server's docroot ?

### ISSUE THREAD

**Issue by aprekates** [klacke/yaws#273]
Following  the example of websockets mentioned on Chapter 14 'WebSocket Protocol Support'
of the http://yaws.hyber.org/doc.yaws  yaws manual .(manual version 7/10/2015)
i come upon this problem:

[websockets_example_endpoint.yaws](https://github.com/klacke/yaws/blob/master/www/websockets_example_endpoint.yaws)  in the end will give output
 {websocket, CallbackMod, Opts}
And let's say that CallbackMod = basic_echo_callback  

If the basic_echo_callback.beam is in the docroot of the virtual server then in the
logs we'll see that file is not found.

By searching man yaws and guessing i put it in /usr/lib/yaws/custom/ebin and the example worked.

Is there a way to make it work but keeping those callback beam file inside each virtual_server docroot dir?

Thanks
 Alexandros

**Comment by vinoski** [comment]
You can use one or more `ebin_dir` directives at the global level of your config to add directories the Erlang module load path.

**Comment by aprekates** [comment]
Thanks for the quick response! I'll try it.

**Comment by vinoski** [comment]
I assumed `ebin_dir` was sufficient to get this working? If so, I'd like to close this issue.

**Comment by aprekates** [comment]
Yes. it worked . thanks
