### ISSUE TITLE
is_default config directive depracated?

### ISSUE THREAD

**Issue by aprekates** [klacke/yaws#274]
In the manual (ch. 13.3) directive is_default is mentioned.

But in my installation (debian 8 with yaws 1.98) 'man yaws.conf'
dosnt mention 'is_default'.

I came searching whilte tryint to figure how to set up a default virt server in case i use the ip to access my
vps.

For time being i am ok by using 
```
<server www>
....
</server>
```

**Comment by vinoski** [comment]
According to git, `is_default` was added 16 Feb 2004 and removed 17 Feb 2004. I'm surprised that leftover remnant in the documentation has survived this long!

**Comment by aprekates** [comment]
Ok. thanks again for the quick feedback.
