### ISSUE TITLE
erlang 19.0 warnings as errors

### ISSUE THREAD

**Issue by jaynel** [klacke/yaws#277]
Using erlang 19.0 causes problems compiling yaws_ls.erl:

```
yaws_ls.erl:273: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
yaws_ls.erl:278: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
make[2]: *** [../ebin/yaws_ls.beam] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [deps] Error 2
```

**Comment by jaynel** [comment]
Removing -Werror from include.mk reveals the following other warnings with 19.0:

```
yaws_ctl.erl:60: Warning: random:seed/3: the 'random' module is deprecated; use the 'rand' module instead
yaws_ctl.erl:61: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
yaws_ctl.erl:70: Warning: random:seed/3: the 'random' module is deprecated; use the 'rand' module instead
yaws_ctl.erl:71: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead

yaws_session_server.erl:158: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
```

**Comment by capflam** [comment]
I will fix that very soon. Thanks @jaynel

**Comment by klacke** [comment]
I guess this is sufficiently boring to merit a new release.
I see all the test go through after the fix for this.

I'll build a new tagged release, 2.0.3

/klacke

**Comment by vinoski** [comment]
@klacke can we hold off on a release until we get issue #274 fixed and also resolve [this conversation](https://github.com/klacke/yaws/commit/8c0773f10be56599b8602c3bbecd2025904369fd)? @capflam was working on the fix for the second issue, and I emailed you both about the `is_default` issue earlier today.

**Comment by klacke** [comment]
Sure - I did build one though. But let's hold back on the announcement.
Looking through the commit log, some good stuff is there.

/klacke

**Comment by vinoski** [comment]
Also, do we want to include [this pull request](https://github.com/klacke/yaws/pull/272)?

**Comment by klacke** [comment]
I think we do, we're using it a Cisco/Tail-f

The usecase is that we have an, application, using yaws as
embedded ws. Now we want to export an erlang API that can manipulate
the embedded ws config. These functions make the API independent
of .hrl files.

/klacke

**Comment by vinoski** [comment]
OK, I think everything is in now and we're ready for 2.0.3.
