### ISSUE TITLE
CallbackMod from out/1 can't contain underscores?

### ISSUE THREAD

**Issue by aprekates** [klacke/yaws#280]
Trying some simple websocket examples i had  one example where websocket connection couldnt be established and terminated with 1006.

Problem was solved after reming the underscores that there were in CallbackMod returned from out/1 -> {websocket, CallbackMod,Options)

**Comment by vinoski** [comment]
You'll need to show the actual code that was causing the problem.

**Comment by aprekates** [comment]
The 3 files below are in a subdir of a docroot of a virtual server defined in yaws.
Also i've set a dir where the beam files of websocket callbacks will be placed.

<erl>
  out(A) -> {websocket, wsserverside, []}.
</erl>
eas_server.yaws (END)


-module(wsserverside).
-export([handle_message/1]).

handle_message({text, Message}) ->
        {reply, {text, Message}}.
wsserverside.erl (END)



    
    <script>
    
     window.onload = function() {
     document.getElementById('clickbtn').addEventListener('click', sendMessage, false);
     document.getElementById('connectbutton').addEventListener('click', connect, false);
     }

     function connect() {

        ws = new WebSocket("ws://myserverurl/erl_app_skeletos/eas_server.yaws");
     
         ws.onopen = function(evt) {
             writeStatus("connected");
          }

         ws.onclose = function(evt) {
           writeStatus("disconnected");
         }

          ws.onmessage = function(evt) {
            writeStatus("response: " + evt.data);
         }

          ws.onerror = function(evt) {
            writeStatus("error: " + evt.data);
         }

      }

      
      // this function be called when a message is sent from the erlang server over ws
      function writeStatus(message) {
        var html = document.createElement("div");
        html.setAttribute("class", "message");
        html.innerHTML = message;
        document.getElementById("counter").appendChild(html);
      }

      function disconnect() {
      ws.close();
      }

     
      function sendMessage() {
         mgs = "click" ;
      //    var msg = document.getElementById('messagefield').value
         ws.send(msg);
      }

    </script>
  </head>
  <body>
   
    <button id="connectbutton">Connect</button>
   <button id="clickbtn">Click the erlang server! </button>
    <div id="counter"></div>
 </body>


</html>
(END)

**Comment by vinoski** [comment]
So are you saying that using `wsserverside` for the module name works, but something like `ws_server_side` doesn't?

**Comment by aprekates** [comment]
yes.

**Comment by capflam** [comment]
That's strange, because examples provided with Yaws contain underscores... I will investigate.

**Comment by capflam** [comment]
Well, It works for me. You have a typo in your javascript, in `sendMessage`. You declare `mgs` instead of `msg`. But, out of it, your example works, with or without underscores in the callback module name.

**Comment by aprekates** [comment]
thanks for the quick feedback and the typo.
i'll check again

**Comment by aprekates** [comment]
I tried again. As soon i do the change to ws_server_side.erl (compiile,mv to callbacks dir, check perms) 
connection error 1006.
Could it be a minor bug in older versions?  I use Erlang/OTP 17 [erts-6.2]  in debian 8 Jessie

**Comment by vinoski** [comment]
Erlang module names typically contain underscores, so it's unlikely this is a bug in any version. Can you check the yaws log to see if there are any relevant messages about this problem?

**Comment by capflam** [comment]
It should work. I checked with this version and everything works fine. I'm running Erlang/OTP 18.
Could you start Yaws in interactive mode and trying to trace yaws_websockets calls:
```
1> dbg:tracer().
{ok,<0.58.0>}
2> dbg:p(all, call).
{ok,[{matched,nonode@nohost,43}]}
3> dbg:tpl(yaws_websockets, dbg:fun2ms(fun(_) -> return_trace(), exception_trace() end)).
{ok,[{matched,nonode@nohost,65},{saved,1}]}
```
And see where the error occurred. It will be very verbose. If you prefer, you can record everything in a file with the `script` command and then post this file.

**Comment by aprekates** [comment]
I tried first the var/log/report.log of yaws:

=ERROR REPORT==== 29-Jul-2016::06:06:23 ===
Failed to start websocket process: {badarg,
[{erlang,register,[counter,<0.5997.1>],[]},
 {ws_server_side,init,1,
 [{file,"ws_server_side.erl"},{line,14}]},
   {yaws_websockets,init,1,
 [{file,"yaws_websockets.erl"},
   {line,167}]},
{gen_server,init_it,6,
 [{file,"gen_server.erl"},{line,306}]},
 {proc_lib,init_p_do_apply,3,
 [{file,"proc_lib.erl"},{line,237}]}]}

**Comment by vinoski** [comment]
The log shows `ws_server_side:init/1` is calling `erlang:register(counter, Pid)` and getting a `badarg` exception. The [`register` documentation](http://erlang.org/doc/man/erlang.html#register-2) explains that `badarg` occurs under the following conditions:

 1. `badarg`
      * If PidOrPort is not an existing local process or port.
 1. `badarg`
     * If RegName is already in use.
 1. `badarg`
    * If the process or port is already registered (already has a name).
 1. `badarg`
    * If RegName is the atom undefined.

My guess is that it's reason 2 causing the problem: a process with the name `counter` is already running when you run `ws_server_side:init/1` and try to register a process with the name `counter` again. In your code, try changing whatever code looks like this:

    register(counter, Pid),

to something more like this:

    case whereis(counter) of
        undefined -> register(counter, Pid);
        Pid -> ok
    end,

**Comment by aprekates** [comment]
strange. that code was in an older version of ws_server_side.erl  
The current one version is the shorther and simpler that i wrote in my 2nd reply in that issue thread. 
And i'm sure that i overwrite the relative beam code before reloading my webpage.

**Comment by aprekates** [comment]
Those the two files i use for the test (src code is the simple one as i just mentioned)
root@enousvps:/var/www/yaws_default/ws_callbacks # ls -alt  
-rw-r--r-- 1 yaws yaws  608 Jul 28 16:28 wsserverside.beam 
-rw-r--r-- 1 yaws yaws  612 Jul 28 16:16 ws_server_side.beam 

Could it be some 'cache' thing?

**Comment by capflam** [comment]
Be careful to load the right module and to restart the erlang VM when it changes. Hot upgrades are possible, but for test purpose, this is safer. You can get information on your module as following:

```
7> ws_server_side:module_info(compile).
```

But as @vinoski said, underscores are allowed in the modules name. So the problem comes from your code or your configuration.

**Comment by aprekates** [comment]
Finally i restarted yaws and problem dissapear.
I guess after reading about modules , how both old and new version can coexist and by the backtrace
that that must happedn in my case.
I've changed ws_server_side while it's old version was used.

Thanks again for the quick and helpfull respone of both of you.
