### ISSUE TITLE
What happen to official website of yaws?

### ISSUE THREAD

**Issue by javidG** [klacke/yaws#285]
I need access to official website of yaws, Why is it down?

**Comment by vinoski** [comment]
Good question! I'll ping Klacke and see what's up.

**Comment by vinoski** [comment]
BTW @javidG as a temporary workaround if you clone the yaws repo, build it, and run it locally, you'll have the same website as the Yaws official website.

**Comment by javidG** [comment]
That, I have already done though I would still want to know what's going on at yaws,   Thank you

**Comment by klacke** [comment]
Will check tonight. Thanks 
/klacke 

On September 7, 2016 11:48:30 PM GMT+02:00, javidG <notifications@github.com> wrote:
>That, I have already done though I would still want to know what's
>going on at yaws,   Thank you
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/klacke/yaws/issues/285#issuecomment-245430251

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by klacke** [comment]
Fixed.

Thanks

/klacke
