### ISSUE TITLE
feature request: rewrite_yaws_compile

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#288]
I just noticed there is work in progress in improving yaws_compile. I wonder if it is possible to add an API to check syntax for example by creating `yaws_compile:compile_file(File, Opts)` that permits some `compile:file/2` options. Thanks.

**Comment by capflam** [comment]
`yaws_compile` is called by a Yaws process, in `yaws_server` module. So, options, if any, should be got from the configuration (the global part) or something similar. And options should be the same for all scripts over all vhosts.
A good solution to customize scripts compilation is to use `-compile` attribute inside a `<erl>` block.

Do you have any use-cases in mind that cannot be solved using `-compile` attribute?

**Comment by leoliu** [comment]
yes. `-compile` is great when you want it for both development and production. otherwise one often forgets to remove it after development. Remember the dreadful `-compile(export_all)` that has been left in places where it shouldn't be.

This feature is more of a development tooling allowing one to quickly check syntax without wring any yaws temp modules and the extra work of cleaning them up.

**Comment by capflam** [comment]
Well, that's a good point. I'll try to do it. These options will also be used during the compilation of modules pointed by the `src_dir` directive. It will be a global option directive.

**Comment by capflam** [comment]
Hum, by checking the `compile` documentation, it already exists a way to "customize" compiler options by setting the environment variable `ERL_COMPILER_OPTIONS`. I guess it does the job, doesn't it ?

**Comment by leoliu** [comment]
yes, it can partly do the job but is unwieldy because if I setenv in an editor such as emacs it has global effect.

**Comment by capflam** [comment]
You just need to set it on the command line to avoid any side effect. For example:
```bash
  $> ERL_COMPILER_OPTIONS="[export_all]" /path/to/bin/yaws
```
I understand your needs, but IMHO, it is doable to deal with environment variables on a development platform without too much pain. I think this workaround is simple enough to not require a specific development.

**Comment by leoliu** [comment]
Indeed `ERL_COMPILER_OPTIONS` is cut for command-line use and probably the reason it is such an awfully fit for editor integration. To some degree it is worse than `-compile`. Imagine fire up yaws for checking syntax and then restart it for compile, or vice versa. In a development session you probably want both at different times. So `ERL_COMPILER_OPTIONS` is not for me personally. I think `yaws_compile:compile_file/2` is a cleaner solution just like `compile:file/2` is.

I was looking for something like this a few months ago and settled with `yaws_compile:compile_file/1` with the annoyance of either having temp files in the project or lots of random modules in ~/.yaws.

Anyway it is not the end of the world if not implemented. I'll continue with my old solution.

**Comment by capflam** [comment]
Sorry to bother you, but I wish to understand your usage. How do you check or compile your scripts ? The expected way to do is to use the Yaws startup script. To check a script, you should use `yaws --check <SCRIPT>`. This will parse the script, create modules corresponding to `<erl>` blocks and compile them.
When you talk about a compile phase, what do you mean exactly ? is it to call `yaws_compile:compile_file/1` by hand or launch Yaws and request the right script in HTTP ?

Finally, for modules generated during scripts parsing, it is boring, you're right. I kept this way to do to avoid any breakage. I'll see with @vinoski and @klacke if there is any reason to keep these files.
Just note that `~/.yaws` directory is used as temporary directory for the running instances of Yaws.

**Comment by leoliu** [comment]
`yaws --check ...` uses `yaws_compile:compile_file/1` so it is not a syntax check but compilation to a different directory (probably the root_dir of the vhost if I remember correctly).

There are a few ways to make use of `yaws_compile:compile_file/2`. For example, one can wrap `yaws_compile:compile_file/2` into a easily rpc-callable function taking inspiration from `yaws_ctl:check/1`, then do the rpc using `distel` or (less convenient) eshell running in emacs. Other editors can invent their ways of using it.

My workflow involves very little about the system shell whose sole purpose is to bring up a distributed erlang node aka `rebar3 shell`.

**Comment by capflam** [comment]
Ok, I see now. So I'll add `yaws_compile:compile_file/2`. And because this is for an integration with ide tools, I'll do it without any directive in the configuration.

Just an observation, `yaws_compile` is a private module. it's unlikely but changes can be done on its API if necessary without other warning than a commit message. So, you can use it of course, but with caution.

**Comment by leoliu** [comment]
Thanks. Look forward to this feature ;)

**Comment by leoliu** [comment]
Hi @capflam,

I am reading the `rewrite_yaws_compile` branch and like what I see. If I understand the code correctly `yaws_compile` no longer change the module names on every compile. So this will remove my concerns of running `yaws_compile` frequently for example on every keystroke in emacs.

BTW, is there a reason not to support `{ok, Module}` and `{ok, Module, Warnings}` in `yaws_compile:compile_erlang_block/2`? which are the return values when `strong_validation` is passed to `compile:file/2`.

I will build the branch and test it for real later today.

**Comment by capflam** [comment]
Hi @leoliu,

I received one of your comment by email about the support of `strong_validation` option. But, I cannot find it on github. BTW, are you always interested by this feature? Because this is doable. The idea would be to skip `<erl>` blocks when no code is generated.

**Comment by leoliu** [comment]
hi @capflam,

I deleted it by mistake. Yes that's what I meant for syntax check i.e. passing the `strong_validation` flag. The syntax check can be run much more frequently or even automatically by IDEs.

How do you mean by skipping `<erl>` block? it will have to go through `compile:file/2`, right?

**Comment by capflam** [comment]
Yes, `compile:file/2` will be called in any cases. But, because no code is generated when `strong_validation` is used, in the result of `yaws_compile:compile_file/2`, each `<erl>` block will be skipped. Concretely, the normal output `{mod, Line, Script, NumChars, Mod, Fun}` will be replaced by `{skip, NumChars}`.

**Comment by capflam** [comment]
@leoliu, I've pushed it if you want to check.

**Comment by leoliu** [comment]
hi @capflam,

I built and ran it for real. everything seems working. Except the error reports still refer to the generated erl files. For example:

```
=ERROR REPORT==== 19-Sep-2016::18:57:02 ===
Dynamic compile error: /Users/leo/sources/erlang/yaws/www/websockets.yaws:530:
 syntax error before: 
generated file at: /Users/leo/.yaws/yaws/default/m_32423556_3.erl
```

BTW, is there any good reason to keep the generated files?

**Comment by leoliu** [comment]
Compiling `yaws/www/bindings.yaws` only generates two modules but there are 4 `<erl>` blocks. Is this correct?

**Comment by capflam** [comment]
Actually, there are 2 `<erl>` blocks, the header and the footer. The 2 others are escaped because of `<verbatim>` tag.
About module references in error messages, you're right. This is no more pertinent.

**Comment by leoliu** [comment]
You are right about `bindings.yaws`.

Another issue is

```
report_compile_warnings(Comp, Warnings) ->
    case Comp#comp.use_yfile_name of
        true  -> report_warnings(Comp, Warnings);
        false -> ok
    end.
```

which means warnings are never reported unless `Comp#comp.use_yfile_name` is true. I find this option hackish and unclean in that it can have implications (suppressing warnings) that you only find out by checking the source.

Maybe that should be removed and instead make `yaws_ctl:check/1` use `strong_validation`.

**Comment by capflam** [comment]
Warnings are only reported when a script is checked. During page rendering, warnings are ignored. This is the expected behavior.

`use_yfile_name` process variable is probably not the best name, but its purpose is to know when we check a script, so we can report warnings/errors on the standard output. I will rename `use_yfile_name` to avoid mistakes.

If you need to get warnings, you can use `warnings_as_errors` option. So script compilation will fail. In such case, I will add warnings in the result.

**Comment by leoliu** [comment]
ok. `warnings_as_errors` works for me. BTW, I like the new error format which is ready for emacs's `compile.el`. Looks like all my concerns are addressed nicely. Many thanks for the hard work.

**Comment by capflam** [comment]
Nice ! Thanks for you help and your feedback. I'll merge it in master very soon.
