### ISSUE TITLE
Support unicode in path docroot 

### ISSUE THREAD

**Issue by Kvaz1r** [klacke/yaws#290]
I tried used this lines in yaws.conf:

```
<server localhost>
    port = 8001
    listen = 127.0.0.1
    docroot = "E:\СамПо\Web\YAWS\Hello world"
</server>
```

and get error when start:

```
=INFO REPORT==== 20-Oct-2016::21:11:50 ===
Warning, Skip invalid docroots at line 120 : e:/╨б╨░╨╝╨Я╨╛/Web/YAWS/Hello world
1>
=ERROR REPORT==== 20-Oct-2016::21:11:50 ===
Yaws: bad conf: No valid docroot configured for virthost 'localhost' (port: 8001
) terminating
```

Is yaws has support unicode in conf file?

**Comment by capflam** [comment]
Hi @Kvaz1r,

In Erlang, by default, files are opened using latin1 encoding. There is an option to choose the encoding but it is not supported in Yaws. Here is a [quick patch](https://gist.github.com/capflam/5491516faa7024435d8200e068f505d2) that should do the trick for now. I will try to push a proper fix very soon that will let users choose the encoding.

Thanks

**Comment by Kvaz1r** [comment]
good,thanks.

**Comment by capflam** [comment]
Hi,

I finally got the time to push a fix. To read unicode config file, you must call the Yaws script with the option `--encoding unicode` or set the application environment variable `{encoding, unicode}`
