### ISSUE TITLE
Is it mandatory to restart yaws to see change in callback dirs?

### ISSUE THREAD

**Issue by aprekates** [klacke/yaws#291]
In setting up some simple websocket examples i noticed
after changing a beam callback file  only by restarting yaws
changes will be visible.
Can we avoid that?
Maybe it's a cache thing and we could clear cache so yaws pulls new code?

**Comment by capflam** [comment]
Hi,

You can reload a module using Yaws script:
```erlang
 $> yaws --load my_module
````
Another solution is to use `src_dir` in the global part of your config file. Yaws will compile all erlang modules found, recursively, in source directories. The compilation occurs when the configuration is loaded or reloaded.

**Comment by aprekates** [comment]
Sorry for the late response.

#yaws --load module or # yaws --status etc all give me :
No yaws system responds

**Comment by capflam** [comment]
This is probably because you set a specific `id` to your Yaws instance. Check the `id` value in your configuration (It is `default` when unset). Then use it when you call Yaws script:

```
$> yaws --id {MYNAME} --load module
```

You can also get name of your Yaws instance using following Erlang snippet:
```erlang
{ok, GC, _} = yaws_server:getconf(),
ID = yaws:gconf_id(GC),
...
```

**Comment by aprekates** [comment]
That worked finaly (but if i execute it as root i'get also many messages.

 sudo -H -u yaws bash -c 'yaws --status --id debian_yaws'

chomwitt@enous3:/$ id
uid=1000(chomwitt) gid=1000(chomwitt) ομάδες=1000(chomwitt),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),33(www-data),44(video),46(plugdev),108(netdev),110(lpadmin),113(scanner)
chomwitt@enous3:/$ sudo -H -u yaws bash -c 'yaws --status --id debian_yaws'
IP Port Connections Sessions Requests
0.0.0.0 8443 0 1 0
0.0.0.0 8080 0 1 0

 Uptime: 1 Days, 2 Hours, 4 Minutes  
chomwitt@enous3:/

root@enous3:~# id
uid=0(root) gid=0(root) ομάδες=0(root)
root@enous3:~#  sudo -H -u yaws bash -c 'yaws --status --id debian_yaws'
{error_logger,{{2016,12,3},{16,46,38}},std_error,"File operation error: eacces. Target: .. Function: read_file_info. Process: code_server."}
{error_logger,{{2016,12,3},{16,46,38}},std_error,"File operation error: eacces. Target: ./standard_error.beam. Function: get_file. Process: code_server."}
{error_logger,{{2016,12,3},{16,46,38}},std_error,"File operation error: eacces. Target: ./supervisor_bridge.beam. Function: get_file. Process: code_server."}
{error_logger,{{2016,12,3},{16,46,38}},std_error,"File operation error: eacces. Target: ./user_sup.beam. Function: get_file. Process: code_server."}
{error_logger,{{2016,12,3},{16,46,38}},std_error,"File operation error: eacces. Target: ./user.beam. Function: get_file. Process: code_server."}
{error_logger,{{2016,12,3},{16,46,38}},std_error,"File operation error: eacces. Target: ./kernel_config.beam. Function: get_file. Process: code_server."}
{error_logger,{{2016,12,3},{16,46,38}},std_error,"File operation error: eacces. Target: ./queue.beam. Function: get_file. Process: code_server."}

=ERROR REPORT==== 3-Dec-2016::18:46:38 ===
File operation error: eacces. Target: .. Function: read_file_info. Process: code_server.

=ERROR REPORT==== 3-Dec-2016::18:46:38 ===
File operation error: eacces. Target: ./standard_error.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Dec-2016::18:46:38 ===
File operation error: eacces. Target: ./supervisor_bridge.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Dec-2016::18:46:38 ===
File operation error: eacces. Target: ./user_sup.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Dec-2016::18:46:38 ===
File operation error: eacces. Target: ./user.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Dec-2016::18:46:38 ===
File operation error: eacces. Target: ./kernel_config.beam. Function: get_file. Process: code_server.

=ERROR REPORT==== 3-Dec-2016::18:46:38 ===
File operation error: eacces. Target: ./queue.beam. Function: get_file. Process: code_server.
