### ISSUE TITLE
Update to 2.0.4

### ISSUE THREAD

**Issue by tschuett** [klacke/yaws#292]
We updated to 2.0.4 this week and ran into a few issues with yaws_dynopts.

compare_version fails for certain Erlang versions, e.g. 18.0.3
```
> yaws_dynopts:compare_version("7.0.3","7.0").
** exception error: no function clause matching yaws_dynopts:compare_version1(["3"],[]) (yaws_dynopts.erl, line 99)
```
Our temporary solution is https://github.com/scalaris-team/scalaris/commit/defe44a7b2a2e1a2714322261859820470191c62

We automatically build otp/master and run dialyzer over scalaris and therefore yaws. In https://github.com/erlang/otp/commit/a30254355bc9798348471878009b6e063ad26fca Erlang removed a bunch of deprecated functions which causes new trouble with dynopts.

The dynamic selection does not help here anymore. The static analyzer will always complain about the non-existent rand_bytes function.
```
rand_bytes(N) ->
    case have_crypto_strong_rand_bytes() of
        true  -> crypto:strong_rand_bytes(N);
        false -> (fun crypto:rand_bytes/1)(N)
end.
```
Here the fix is easy:
```
rand_bytes(N) ->
   crypto:strong_rand_bytes(N).
```
```strong_rand_bytes``` is old enough. In the other functions either old or new dialyzers will complain about non-existent funcitons. You may want to lift the ifdefs one level up. Our tempory (and brutal) solution is here https://github.com/scalaris-team/scalaris/commit/e4ca4f3ce944c5e5cb3dadf8376714b43eb7b687

**Comment by capflam** [comment]
About `yaws_dynopts:compare_version/2`, I'll quickly push the fix. I don't know how I missed it, thanks !

`crypto:strong_rand_bytes/1` is available in R16B01, the oldest Erlang/OTP release supported by Yaws. So, as you said, it is safe to always use it and remove crypto:rand_bytes/1 support.

About `erlang:now/0`, it has been deprecated in Erlang/OTP 18. So I'm surprised that dialyzer does not complain about it. And, for Erlang/OTP >= 18, the compilation will fail.

Finally, for `ssl:connection_information/2`, it is a good catch. This function has been introduced in Erlang/OTP 18. So I'll added a wrapper in `yaws_dynopts` to handle that.

**Comment by tschuett** [comment]
IIRC, the compiler warns about ```erlang:now/0``` being deprecated. dialyzer does not seem to care. Our builds for 19.0 and 19.1 were green today. I guess the function is still there.

I forgot to mention the ssl function. I ran dialyzer with R14B04 which complained about the missing function. We do not use ssl and yaws still seems to work for us in R14B04.

**Comment by capflam** [comment]
By default, the Yaws compilation fails on warnings. So we cannot have such warnings on upstream. And as for ` crypto:rand_bytes/1`, `erlang:now/0` will be removed a day or another. So we must keep the wrapper around this function.

We have chosen to have dynamic checks for deprecated and unsupported features in Erlang/OTP releases, instead of a static ones (using `-ifdef`), because Yaws can be compiled on a release and run on another one. This often happens when you use the Erlang packages of your distribution.

About R14 and R15, you should be careful because some functions used in Yaws does not exit on these releases or are buggy:

* `crypto:hash/2`: introduced in R15B02
* `inet:parse_strict_address/1`: introduced in R16A
* `fillib:wildcard/1,2`: is buggy in R15B03 and previous
* `unicode` module has a bug in R14B04

**Comment by capflam** [comment]
@tschuett, I pushed some fixes in the branch issue_292. Could you check if everything is ok for you ?

**Comment by tschuett** [comment]
LGTM. I will update once the otp/master will remove ```erlang:now/0```. My problem is still with
your wrapping technique to fool dialyzer. https://github.com/klacke/yaws/commit/d41757770e731f67b842e2fd9bb21be876c3d7ac. The otp/master dialyzer understands what is going on here. I just tried this with ```crypto:mpint/1```
Call to missing or unexported function crypto:mpint/1

**Comment by capflam** [comment]
Ok, thanks, I will merge it in master. But I'm surprised you still have troubles with dialyzer. I've done some tests with releases R16B01 and 19.1, and there was no error. Here is the output I had:

```
$> .../erlang/19.1/bin/dialyzer  --plt yaws.plt -r ebin 
  Checking whether the PLT yaws.plt is up-to-date... yes
  Compiling some key modules to native code... done in 0m0.24s
  Proceeding with analysis...
yaws.erl:1677: The pattern 'false' can never match the type [[any()]]
yaws.erl:2759: Guard test Ret::'file' == 'fd' can never succeed
yaws.erl:2767: Guard test Ret::'file' == 'binfd' can never succeed
yaws_api.erl:2606: The pattern 'false' can never match the type 'true'
yaws_config.erl:671: The pattern 'false' can never match the type 'true'
yaws_ctl.erl:518: Function hup/1 has no local return
yaws_ctl.erl:523: Function stop/1 has no local return
yaws_ctl.erl:527: Function status/1 has no local return
yaws_ctl.erl:530: Function load/1 has no local return
yaws_ctl.erl:548: Function trace/1 has no local return
yaws_ctl.erl:551: Function debug_dump/1 has no local return
yaws_ctl.erl:554: Function stats/1 has no local return
yaws_ctl.erl:556: Function running_config/1 has no local return
yaws_revproxy.erl:668: The pattern 'true' can never match the type 'false'
yaws_sendfile.erl:53: The pattern 'false' can never match the type 'true'
yaws_sup_restarts.erl:49: The pattern 'false' can never match the type 'true'
Unknown functions:
  eprof:profile/1
  eprof:start/0
  erlsom:add_model/2
  erlsom:add_xsd_file/3
  erlsom:add_xsd_model/1
  erlsom:compile_xsd/1
  erlsom:compile_xsd_file/2
  erlsom:scan/2
  erlsom:scan_file/2
  erlsom:write/2
  erlsom:write_hrl/2
  erlsom_compile:compile_parsed_xsd/2
  erlsom_lib:getTargetNamespaceFromXsd/1
  erlsom_lib:localName/1
  erlsom_lib:toUnicode/1
  ibrowse:send_req/5
  ibrowse:send_req/6
  ibrowse:start/0
  tags:dirs/1
  xmlrpc_decode:payload/1
  xmlrpc_encode:payload/1
  xmlrpc_http:handle_xmlprc_error/2
  xref:d/1
Unknown types:
  public_key:der_encoded/0
  public_key:private_key/0
 done in 0m12.46s
done (warnings were emitted)
```

```yaws.plt``` is the PLT file generated with yaws Makefile. In R16B01, the output is quite similar.
