### ISSUE TITLE
What is the log format used ?

### ISSUE THREAD

**Issue by aprekates** [klacke/yaws#295]
I checked some log in a debian system in /var/log/yaws/foosite.access and they dont follow the 
https://en.wikipedia.org/wiki/Common_Log_Format , they seem to have identifier at the end?

**Comment by capflam** [comment]
Yaws use the Combined log format, as defined in Apache documentation. This format is exactly the same as the Common Log Format, with the addition of two more fields: The Referer and the User-Agent.

**Comment by aprekates** [comment]
Cool , thanks.
