### ISSUE TITLE
yaws_api:request_url() - Portnumber behind a proxy Server

### ISSUE THREAD

**Issue by YetAnotherErlangProgrammer** [klacke/yaws#297]
Dear Claes Wikstrom,

i am using yaws behind a reverse proxy.
If i use they yaws_api:request_url(A) function i get the Host-Name of the original-request - like expected and i get the port number of the yaws-Server that is hidden behind the proxy.

Your yaws_api:request_url/1  - function starting in line 2541 gets the Hostname from the Header-field (lines 2554 and following) and gets the Port-number from the SC-Variable (lines 2560 and following) The SC-Variable was generated in line 2543. 
if you change the lines 2560 until 2567 like this:

%%%%%%%% Begin of Change %%%%
port = case string:tokens( Headers#headers.host , ":" ) of
  [_,Port1] -> element(  1, string:to_integer( Port1 ) );
  [_] -> undefined
end,,
%%%%% End of Change %%%%%%

Now it returns the Port of the original-Request instead the Port of the yaws-configuration. That might be more what the user of yaws_api:request_url(Arg) expected.

I am not experienced issuing requests here, so i want to apologize for the mistakes i might have made.

if you find that useful i would be happy you make this change.

Regards
Thomas Rackwitz

**Comment by capflam** [comment]
Hi Thomas,

It's a good remark. Using `Host` header in priority is probably the best to do. But when there is no `Host` header, the function must fall back on the Sconf values, as for the `#url.host`. Do not forget that `Host` header is not mandatory for HTTP/1.0 request.

If you want to do the fix, your pull request is welcomed. But be careful, your code snippet does not catch the case where `Host` header is undefined. Maybe you can get `Host` and `Port` in the same `case` clause. As you wish.

**Comment by YetAnotherErlangProgrammer** [comment]
Here is an idea, how to fix it:

```erlang
%% discovers the schema from the arg- and  sconf-structure
schema(#arg{clisock={ssl,_}}) -> 'https';
schema(#arg{}) -> 'http';
schema(#sconf{ssl=undefined}) -> 'http';
schema(#sconf{}) -> 'https'.

%% returns undefined if port is the standardport - otherwise the Port
specialport(#sconf{ssl=undefined,port=80}) -> undefined;
specialport(#sconf{ssl=#ssl{},port=443}) -> undefined;
specialport(#sconf{port=Port}) -> Port.

%% returns a tuple of Host and Port from a given header
hostport(#headers{host=undefined}) -> {undefined,undefined};
hostport(#headers{host=Host}) ->
  case yaws:split_at(Host,$:) of
    {Host,[]} -> {Host,undefined};
    {Host1,Port1} -> {Host1,element(1,string:to_integer(Port1))}
  end.

%% Return the parsed url that the client requested.
request_url(ARG) ->
    SC = get(sc),
    Headers = ARG#arg.headers,
    {abs_path, Path} = (ARG#arg.req)#http_request.path,
    DecPath = yaws_api:url_decode(Path),
    {P,Q} = yaws:split_at(DecPath, $?),
    {Host,Port} = hostport(Headers),
    case #url{scheme=schema(ARG),host=Host,port=Port,path=P,querypart=Q} of 
      U=#url{host=undefined} -> 
             U#url{scheme = schema(SC),
                   host = element(1,yaws:split_at( SC#sconf.servername , $: ) ),
                   port = specialport(SC) };
      U1=#url{} -> U1
    end.
```
As long as i use the fqdn as the servername in the config-file it works.

**Comment by capflam** [comment]
Thanks, I'll check that as soon as possible.

**Comment by capflam** [comment]
Hi Thomas,

I pushed a fix to this issue. I relied on `yaws_api:parse_url/2` instead to get host/port. The result is slightly more simple. Thanks for reporting the issue and for your work on it.
