### ISSUE TITLE
some things not updated after yaws --hup

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#299]
I tried changing global config `server_signature` and then `yaws --hup` but it retained its old value. Bug? I am running Yaws from git master.

**Comment by capflam** [comment]
It should be updated after a reload. Are you sure you have not used an old connection (already opened) to do your tests ? Try to check it with curl before and after a reload to be sure.

**Comment by leoliu** [comment]
Oddly it is updated now. BTW I always use curl to check it.
