### ISSUE TITLE
How to Start Yaws

### ISSUE THREAD

**Issue by SumitFlochat** [klacke/yaws#308]
Hi,

I have used following commands :- 

1. apt-get install yaws
2. yaws
(it gives error).
=INFO REPORT==== 16-May-2017::14:12:33 ===
Yaws: Using config file /etc/yaws/yaws.conf

=INFO REPORT==== 16-May-2017::14:12:33 ===
Yaws: Using global subconfig file /etc/yaws/conf.d/localhost-ssl.conf

=INFO REPORT==== 16-May-2017::14:12:33 ===
Warning, Skip invalid docroots at line 17 : /usr/share/yaws/www

=ERROR REPORT==== 16-May-2017::14:12:33 ===
Yaws: bad conf: No valid docroot configured for virthost 'localhost' (port: 8443) terminating

How to fix it ? Can anyone help?

**Comment by ningzhang** [comment]
Try creating a file with the following content and name the file "yaws.conf":

```
id = "Test"

<server localhost>
    listen = 0.0.0.0
    port = 8443
    docroot = .
</server>
```

Then execute:

$```yaws --conf yaws.conf```

Note that you need a valid "docroot" field in the configuration. In the example above, the current directory is used as the docroot.

**Comment by SumitFlochat** [comment]
Thank you
It worked...

**Comment by ningzhang** [comment]
Cheers.
