### ISSUE TITLE
gen_event handler yaws_log_file_h crashed on yaws startup

### ISSUE THREAD

**Issue by jvshore** [klacke/yaws#311]
I installed Erlang/OTP 20 on centos 7 first, and then yaws 1.98. On yaws startup I am getting the following error: 

** gen_event handler yaws_log_file_h crashed.
** Was installed in error_logger
** Last event was: {info_report,<0.52.0>,
                                {<0.33.0>,progress,
                                 [{application,crypto},
                                  {started_at,nonode@nohost}]}}
** When handler state == {<0.71.0>,"/var/log/yaws/report.log",[]}
** Reason == {function_clause,
                 [{error_logger_file_h,write_event,
                      [{<0.71.0>,"/var/log/yaws/report.log",[]},
                       {info_report,<0.52.0>,
                           {<0.33.0>,progress,
                            [{application,crypto},
                             {started_at,nonode@nohost}]}}],
                      [{file,"error_logger_file_h.erl"},{line,106}]},
                  {error_logger_file_h,handle_event,2,
                      [{file,"error_logger_file_h.erl"},{line,71}]},
                  {gen_event,server_update,4,
                      [{file,"gen_event.erl"},{line,573}]},
                  {gen_event,server_notify,4,
                      [{file,"gen_event.erl"},{line,555}]},
                  {gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,296}]},
                  {proc_lib,init_p_do_apply,3,
                      [{file,"proc_lib.erl"},{line,247}]}]}

Please help me determine the cause that can point to potential fix

**Comment by vinoski** [comment]
Yaws 1.98 is very old, and this was fixed a long time ago. Please use version 2.04.
