### ISSUE TITLE
[feature] Make Arg returned from out/1 more useful

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#323]
Commit `0e1a7c3c4b60c56e25349fb1c9a739c539425556`: Fix handle_out_reply/5 function added a comment `if RetVal == #arg{}, replace ARG in recursion`. I have found this desirable.

I have a root appmod that does a bunch of stuff among them store some data in `#arg.state` but I can't find a way to have it available to `out/1` function, for example, in `{yssi, "products.yaws"}`. Thoughts?

**Comment by leoliu** [comment]
@vinoski Thanks a lot.

**Comment by leoliu** [comment]
I wonder if the man page for `yaws_api` needs update for this change?

**Comment by vinoski** [comment]
Updated the `yaws_api` man page and the `yaws.tex` documentation in 9158f55.

**Comment by leoliu** [comment]
Thanks Steve.
