### ISSUE TITLE
yaws_api:filter_parse/3 bug

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#324]
The function says return a list of values but erroneously return a tuple. Could someone take a look and also consider if returning `{ok, Vs}` is better than `Vs`? Thanks.

**Comment by vinoski** [comment]
Clearly, the code returns either a tuple or `undefined`, and this has been true for a long time &mdash; I traced the `list_to_tuple` call back over a decade, and the comment and the `list_to_tuple` call have been there together for quite awhile. Changing the return value now would likely break user code, so I won't change that, but I'll change the comment.

**Comment by leoliu** [comment]
Thanks for the clarification.
