### ISSUE TITLE
Node crash due to missing runtime dependency

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#331]
Cannot start (get a crash dump instead) a release with embedded Yaws due to `{undef, {compile, file, [.....]}}`. Yaws has run-time dependency on OTP `compiler` which is missing in the `yaws.app` file.

**Comment by vinoski** [comment]
If you're building Yaws via automake, you can add `compiler` to the `yaws.app` file by passing the `--enable-compiler` command-line option to `configure`. If you're building via `rebar` you can set the OS environment variable `YAWS_APPDEPS=compiler` for the `rebar` build process.

**Comment by leoliu** [comment]
Thanks a lot.
