### ISSUE TITLE
Build from release tarball fails for 2.0.6

### ISSUE THREAD

**Issue by ilovezfs** [klacke/yaws#339]
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/26465/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_yaws/

```
Making install in testsuite
make[1]: *** No rule to make target `testsuite.erl', needed by `../testsuite/testsuite.beam'.  Stop.
make: *** [install-recursive] Error 1
```

This doesn't seem to affect a build directly from the Git repo at 8254d4dba9702245bf8de0195264c08e78eb16ad

**Comment by xyproto** [comment]
I get the same error message when building/packaging the `yaws` package for Arch Linux, for 2.0.6.

`testsuite.erl` is present in git master, but not in the tarball.

**Comment by vinoski** [comment]
I downloaded the 2.0.6 tarball and `testsuite.erl` is definitely there:

    $ tar tf ./yaws-2.0.6.tar.gz | grep testsuite.erl
    yaws-yaws-2.0.6/testsuite/testsuite.erl

Using that tarball, I successfully ran the following to build Yaws 2.0.6 on OS X:

    tar xf yaws-2.0.6.tar.gz
    cd yaws-yaws-2.0.6
    autoreconf -fi
    ./configure
    make all
    sudo make install

I didn't see any errors related to `testsuite.erl` (or any other errors).

**Comment by ilovezfs** [comment]
Sorry I meant @vinoski

**Comment by ilovezfs** [comment]
CC @klacke it would be great to get this fixed.

**Comment by vinoski** [comment]
Yes, I used https://github.com/klacke/yaws/archive/yaws-2.0.6.tar.gz .

**Comment by ilovezfs** [comment]
@vinoski Ah OK. Yeah, that is just the auto-generated source archive tarball, not the release tarball.

**Comment by klacke** [comment]
Hmm, I'm not sure what we should do with this. I wasn't even aware of the archive thing. Neither can I find any settings to not generate these archives. The release we build (through bin/build_release) is the Yaws release.

**Comment by ilovezfs** [comment]
@klacke yeah it cannot be disabled. They're available for all tags on GitHub (it's just a thin wrapper around the `git archive` command).

**Comment by ilovezfs** [comment]
@klacke to be clear it's http://yaws.hyber.org/download/yaws-2.0.6.tar.gz that is broken.

**Comment by klacke** [comment]
Yes, I see this now. All clear. Working on it.

**Comment by ilovezfs** [comment]
Thanks @klacke!

**Comment by klacke** [comment]
Fixed. The problem was related to autotools and the host where I did the final build having an apt-get erlang instead of a source erlang. That problem still remains though, but the current tar ball, the http://yaws.hyber.org/download/yaws-2.0.6.tar.gz is good now.

**Comment by ilovezfs** [comment]
Thanks @klacke! Voilà https://github.com/Homebrew/homebrew-core/pull/29445

**Comment by xyproto** [comment]
Hey presto! https://www.archlinux.org/packages/community/x86_64/yaws/

Thanks @klacke
