### ISSUE TITLE
Stack Trace appears broken in 2.0.6

### ISSUE THREAD

**Issue by crvarner** [klacke/yaws#343]
My co-worker has 2.0.4 and has nice stack traces for errors encountered in appmods, but running the same project it appears my stacktraces all look similar to below:

    ERROR erlang code threw an uncaught exception:
     File: appmod:0
    Class: error
    Exception: undef
    Req: {http_request,'GET',{abs_path,"/test"},{1,1}}
    Stack: [{yaws_server,handle_out_reply,5,
                     [{file,"yaws_server.erl"},{line,3414}]},
        {yaws_server,deliver_dyn_part,8,
                     [{file,"yaws_server.erl"},{line,2886}]},
        {yaws_server,aloop,4,[{file,"yaws_server.erl"},{line,1251}]},
        {yaws_server,acceptor0,2,[{file,"yaws_server.erl"},{line,1074}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

I have seen that this could be due to changes to stacktraces caused by OTP 21

**Comment by vinoski** [comment]
Thanks for reporting this but I believe it's a duplicate of #340, already fixed in master.

**Comment by crvarner** [comment]
Ah okay I thought this was the bit you mentioned was left as is so you could get the fix out quickly. Thanks for the quick response!

**Comment by vinoski** [comment]
@crvarner: if it is the bit I mentioned that isn't fixed yet, please let me know.
