### ISSUE TITLE
Is there any reason to keep yaws_sendfile_drv.c?

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#353]
Erlang has `file:sendfile/5` since R15 so I am wondering if it is time for `yaws_sendfile_drv.c` to go?

Keeping `yaws_sendfile_drv.c` has some downsides. It is painful when using embedded Yaws because `yaws_sendfile` starts it even when it is not needed. It needs extra care when using yaws as rebar3 deps.

At the moment I have a complex setup to deploy to centos from macOS and the setup can be reduced to one line if `yaws_sendfile_drv.c` is no more.

**Comment by vinoski** [comment]
True, it's probably time to retire this. I'll look into it.

**Comment by vinoski** [comment]
I started working on it but I haven't completed it.

**Comment by leoliu** [comment]
@vinoski, thanks for the update.

**Comment by vinoski** [comment]
The only current issue with this work is that some versions of R16 had buggy sendfile support. However, I believe the Yaws policy is to support the five most recent Erlang/OTP releases, so technically we can retire support for R16. I'll have to do that first.

**Comment by leoliu** [comment]
Sounds good. Having OTP 17 as minimal requirement opens up other opportunities such as maps.

**Comment by vinoski** [comment]
@leoliu please have a look at the `drop-yaws-sendfile` branch, which currently passes Travis and builds correctly with `rebar` on Ubuntu. Feedback welcomed.

**Comment by leoliu** [comment]
This is excellent news to the project! Thanks for the work.

I just added this line to rebar.config in a project and it is working like a charm. No complaints so far.

```
{yaws, {git, "https://github.com/klacke/yaws.git", {branch, "drop-yaws-sendfile"}}}
```

**Comment by vinoski** [comment]
This is now rebased to master.

**Comment by leoliu** [comment]
@vinoski I just noticed one small issue. I now use Yaws as a rebar3 dep and after building a release the `yaws-2.0.6` directory looks like this:

```
├── ebin
├── include
└── priv
```

all these subdirectories have a file `Makefile.am` which is unusual.

**Comment by vinoski** [comment]
There's an outstanding issue #262 that was opened a long time ago to add support for `rebar3`. It's been dormant for awhile but I just rebased master to the `rebar3-support` branch and pushed it here. I'd like to make changes specific to `rebar3` on that branch, so can you try it and if the `Makefile.am` issue above is still a problem there, raise a new issue for it? Thanks.

**Comment by leoliu** [comment]
Same issue with `rebar3-support`. See #368.
