### ISSUE TITLE
Unhandled reply fr. do_recv() {error,etimedout}

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#355]
I am seeing this printed in the console:

```
=ERROR REPORT==== 25-Dec-2018::14:44:43.781628 ===
Unhandled reply fr. do_recv() {error,etimedout}
```

which is originated from `yaws:http_recv_request/0`. Is `{error, timeout}` supposed to be `{error,etimedout}`? Another issue is `fr.` is an odd abbreviation.

**Comment by vinoski** [comment]
`{error, timeout}` is valid, and so I've left it alone in 517ca65, but I've added handling for `{error, etimedout}` too, and I've always wanted to fix that log message and so I've done that as well.

**Comment by leoliu** [comment]
@vinoski The change looks good. Thanks.

**Comment by vinoski** [comment]
Rebased 517ca65 to master.

**Comment by leoliu** [comment]
@vinoski I can't find the commit on master. Something wrong?

**Comment by vinoski** [comment]
Yes, apparently there was a network glitch while I pushed it. It's there now, commit 517ca65.

**Comment by leoliu** [comment]
Thanks. Works now.
