### ISSUE TITLE
Support for the X-Content-Type-Options header?

### ISSUE THREAD

**Issue by etnt** [klacke/yaws#362]
Hi guys, 
I wonder if it is possible to optionally add this header for "script" and "style" type of files?

See here for more info about what the header means: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

Cheers!

**Comment by vinoski** [comment]
Is there a reason your code or application can't add this response header itself?

**Comment by vinoski** [comment]
This can now be solved using the extra response headers feature added in commit c625001, so closing this issue.
