### ISSUE TITLE
HAVE_START_ERROR_LOGGER vs HAVE_ERROR_LOGGER_START

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#365]
Check `.yaws/yaws/ID/yaws_dynopts.erl`. Look like a typo for me.

BTW, I am now working exclusively with OTP 21 and Yaws's report.log has become more and more useless as time goes by because it can no longer capture all logs from a release unless produced by `error_logger` which is getting used less and less. i.e. logger is a superset of error_logger so Yaws' report.log is capturing a shrinking subset of logs.

**Comment by vinoski** [comment]
Please open a new issue for the `logger` vs. `error_logger` comment.
