### ISSUE TITLE
Unable to install on Ubuntu 18.04 and OTP 21

### ISSUE THREAD

**Issue by micheleriva** [klacke/yaws#369]
Hi,
I am trying to install Yaws on my Ubuntu 18.04 machine (OTP 21).
I've tried to install it with `apt-get` but after that, if I try to run `yaws` in my shell I get "command not found" error.
I've tryied to build it from source [as written here](http://yaws.hyber.org/configuration.yaws), but after running `./configure --prefix=/usr; make`, I get the following error:

```sh
configure: error: "Could not find pam_appl.h required for pam authentication"
make: *** No targets specified and no makefile found.  Stop.
```
full log [here](https://gist.github.com/micheleriva/d7838155db0a954a8deb2ae92c08880a)

what can I do?
Thanks!

**Comment by vinoski** [comment]
In the [README.md](https://github.com/klacke/yaws/blob/master/README.md) it explains what packages you need to install to build Yaws. The last one in the list is the one you're missing:

> Install build dependencies. Required packages to compile Yaws are (based on debian packages):
>
> build-essential
> autoconf/automake/libtool
> erlang - Required apps:
> erlang-{kernel/stdlib/sasl/erts}
> erlang-compiler
> erlang-crypto
> erlang-xmerl
> libpam0g-dev

**Comment by micheleriva** [comment]
Such a dumb error. I'm sorry and thank you!

**Comment by vinoski** [comment]
No worries, I still forget to install that particularly rpm myself from time to time.
