### ISSUE TITLE
Incorrect handling of unicode chars in request path

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#378]
I just discovered a bug probably from fixing https://github.com/klacke/yaws/issues/329. 404 is returned for any request path that has unicode chars in it. For example place a file `你好.txt` in a directory that is served by yaws and try to view it.

```
The requested URL /%E4%BD%A0%E5%A5%BD.txt was not found on this server.
```

**Comment by leoliu** [comment]
@vinoski This bug is happening again with Yaws 866f3634224358c21bd59b403a6e1c0c936b76dd

**Comment by vinoski** [comment]
That's unfortunate; reopening this issue.

**Comment by vinoski** [comment]
I pushed b703951, which I believe re-fixes this.

**Comment by leoliu** [comment]
@vinoski I can confirm the fix. Thanks a lot.

**Comment by vinoski** [comment]
Thank you!
