### ISSUE TITLE
deflate and vary: accept-encoding header

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#380]
Today I noticed duplicate "Vary: Accept-Encoding" headers from a server I am running. After some inspection I have discovered this behaviour:

I have Yaws' deflate configured only for two mimetypes `text/css` and `application/javascript`. However if I am requesting a `text/html` page which should not be compressed I still have this `Vary: Accept-Encoding` header in the response. I wonder if this is a bug i.e. Yaws' unconditionally add `Vary: Accept-Encoding` header?

**Comment by vinoski** [comment]
Yes, I think it's a bug. Yaws sees that deflate is on and that a non-empty response is being returned, so it's adding the `Vary` header without checking that the mime type of the response is one of those for which deflate is configured.

**Comment by vinoski** [comment]
@leoliu please try the `fix-380` branch if you can, when you get a chance, and let me know your opinion. Thanks.

**Comment by leoliu** [comment]
@vinoski I just tested `fix-380` branch and can confirm the bug is fixed. Thanks.
