### ISSUE TITLE
Time for a 2.0.7 release?

### ISSUE THREAD

**Issue by etnt** [klacke/yaws#381]
Almost exactly one year since 2.0.6.
Isn't it time for a new release now?

**Comment by vinoski** [comment]
Pretty much, but first I'd like the latest commit to master to get about another week of usage to make sure it's ok.

**Comment by etnt** [comment]
Great to hear! Then I can close this issue.

**Comment by leoliu** [comment]
Are we ready for a release?

**Comment by vinoski** [comment]
Done, Yaws 2.0.7 is available. I have not drafted any release notes or such yet, however.
