### ISSUE TITLE
Securely handle multiple content-length headers

### ISSUE THREAD

**Issue by leoliu** [klacke/yaws#384]
I am reading this amazing security [whitepaper](https://portswigger.net/blog/http-desync-attacks-request-smuggling-reborn). Handling multiple CL headers incorrectly is a vulnerability and unfortunately Yaws does it incorrectly.

When there are multiple content-length headers the web server has no idea how much to read from the socket so it seems the only option is to return an error. Unfortunately Yaws picks the last CL header and continues.

The way the Transfer-Encoding header is handled may also be problematic.

**Comment by leoliu** [comment]
@vinoski thanks for fixing the double CL header issue. What do you think of the TE issue? For example if a request has:

```
Transfer-Encoding: chunked
Transfer-Encoding: x
```

It seems the server is in similar situation i.e. has no idea how to proceed.

**Comment by leoliu** [comment]
RFC 7230 3.3.3:

```
If a Transfer-Encoding header field
       is present in a request and the chunked transfer coding is not
       the final encoding, the message body length cannot be determined
       reliably; the server MUST respond with the 400 (Bad Request)
       status code and then close the connection.
```

**Comment by leoliu** [comment]
Attacks: https://hackerone.com/reports/498052

**Comment by vinoski** [comment]
I have some changes in branch `te-fixes-384` for these transfer encoding issues, if you'd like to take a look.

**Comment by leoliu** [comment]
@vinoski 

I just read through the diff and it looks like a thorough treatment of the issue. Thanks for the work. I'll give it a real test once my internet is restored.

For now I have a small concern on the change. The concatenated TE headers are reversed as opposed to the request and because this header might be used elsewhere it could easily lead to buggy code, for example, `dispatchmod`, `appmod` etc might inspect the header too.

**Comment by vinoski** [comment]
Great, thanks for checking.
