### ISSUE TITLE
partial_post_size=nolimit is dangerous?

### ISSUE THREAD

**Issue by MayamaTakeshi** [klacke/yaws#391]
Hi, regarding partial_post_size, the doc says "Setting it to nolimit is potentially dangerous."
What kind of danger would this be?

Would it be some sort of security issue? 
I am asking because I want to use nolimit but since this would be for a non-public server, I don't have security concerns.

**Comment by vinoski** [comment]
The danger here is that a client could post a very large part, so large that the web server process runs out of memory and crashes. It sounds like in your environment, clients are likely to be well behaved, and so using `nolimit` likely won't be a problem for you.

**Comment by MayamaTakeshi** [comment]
Understood. So it will be OK for me to use nolimit. Thanks.
