### ISSUE TITLE
Unable to build with OTP 23.0 RC1

### ISSUE THREAD

**Issue by lucafavatellawork** [klacke/yaws#399]
Symptom:
```
Compiling c_src/epam.c
Compiling c_src/setuid_drv.c
/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status
ERROR: sh(cc c_src/epam.o -m64  -shared  -L"/usr/local/lib/erlang/lib/erl_interface-3.14/lib" -lerl_interface -lei -o priv/lib/epam.so)
failed with return code 1 and the following output:
/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status

ERROR: compile failed while processing /home/builder/workdir/deps/yaws: rebar_abort
make: Leaving directory '/home/builder/workdir/deps'
make: *** [Makefile:74: yaws] Error 1
```

**Comment by vinoski** [comment]
This is already a work-in-progress; I've been working on a branch for 23.0-rc1 locally. There are a number of issues to fix.

**Comment by vinoski** [comment]
BTW, note that the `-lerl_interface` issue is a `rebar` problem, not specifically a Yaws problem. It doesn't happen if you build Yaws using its `automake` build support. The `-lerl_interface` is built into the [value of `ERL_LDFLAGS` in the `rebar` sources](https://github.com/rebar/rebar/blob/master/src/rebar_port_compiler.erl#L676). Since `rebar` is deprecated, I believe this implies that 23.0 will require `rebar3`.

**Comment by vinoski** [comment]
Commit c075071 builds successfully with automake-based builds under Erlang 23.0-rc1. There is one failing test due to a known issue with TLS 1.3 in rc1; presumably this will improve with the next release candidate. Builds with `rebar` do not work, though, as described in the previous comment.

**Comment by lucafavatellawork** [comment]
@vinoski Thanks, one of these days I will try it out.

**Comment by MarcellHarmaci** [comment]
> Builds with `rebar` do not work, though
Then I suppose the README.md should be updated, because it can cause a lot of headache

**Comment by vinoski** [comment]
> > Builds with `rebar` do not work, though
> 
> I suggest the README.md should be updated, because it can cause a lot of headache for people trying to build yaws. At least `autotools` should be the 1st suggestion instead of `rebar`.

@MarcellHarmaci I've updated `README.md`, thanks. For future reference, it's better to start a new issue for something like this rather than comment on a two-year-old closed issue.
